// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary design header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef _VTOP_H_
#define _VTOP_H_  // guard

#include "verilated_heavy.h"
#include "Vtop__Dpi.h"

//==========

class Vtop__Syms;

//----------

VL_MODULE(Vtop) {
  public:
    
    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(reset,0,0);
    VL_IN8(clk_12,0,0);
    VL_OUT8(VGA_R,7,0);
    VL_OUT8(VGA_G,7,0);
    VL_OUT8(VGA_B,7,0);
    VL_OUT8(VGA_HS,0,0);
    VL_OUT8(VGA_VS,0,0);
    VL_OUT8(VGA_HB,0,0);
    VL_OUT8(VGA_VB,0,0);
    VL_IN8(ioctl_download,0,0);
    VL_IN8(ioctl_upload,0,0);
    VL_IN8(ioctl_write,0,0);
    VL_IN8(ioctl_dout,7,0);
    VL_IN8(ioctl_din,7,0);
    VL_IN8(ioctl_index,7,0);
    VL_OUT8(ioctl_wait,0,0);
    VL_IN16(inputs,11,0);
    VL_IN(ioctl_addr,24,0);
    
    // LOCAL SIGNALS
    // Internals; generally not touched by application code
    CData/*0:0*/ top__DOT__uut__DOT__s_12mhz;
    CData/*0:0*/ top__DOT__uut__DOT__s_6mhz;
    CData/*0:0*/ top__DOT__uut__DOT__s_6mhz_n;
    CData/*0:0*/ top__DOT__uut__DOT__phi0;
    CData/*0:0*/ top__DOT__uut__DOT__phi2;
    CData/*0:0*/ top__DOT__uut__DOT__irqres_n;
    CData/*0:0*/ top__DOT__uut__DOT__mpu_clk;
    CData/*0:0*/ top__DOT__uut__DOT__mpu_reset;
    CData/*0:0*/ top__DOT__uut__DOT__hsync_reset;
    CData/*0:0*/ top__DOT__uut__DOT__s_1h;
    CData/*0:0*/ top__DOT__uut__DOT__s_8h;
    CData/*0:0*/ top__DOT__uut__DOT__s_32h;
    CData/*0:0*/ top__DOT__uut__DOT__s_16v;
    CData/*0:0*/ top__DOT__uut__DOT__s_256h_n;
    CData/*0:0*/ top__DOT__uut__DOT__s_6_12;
    CData/*0:0*/ top__DOT__uut__DOT__ea_addr_clk;
    CData/*0:0*/ top__DOT__uut__DOT__ea_ctrl_clk;
    CData/*0:0*/ top__DOT__uut__DOT__hs_clk;
    CData/*0:0*/ top__DOT__uut__DOT__hs_set;
    CData/*0:0*/ top__DOT__uut__DOT__blank_clk;
    CData/*0:0*/ top__DOT__uut__DOT__tb_h_ck;
    CData/*0:0*/ top__DOT__uut__DOT__tb_v_ck;
    CData/*0:0*/ top__DOT__uut__DOT__tb_h_ctr_clr;
    CData/*0:0*/ top__DOT__uut__DOT__tb_v_ctr_clr;
    CData/*0:0*/ top__DOT__clk_12;
    CData/*0:0*/ top__DOT__reset;
    CData/*7:0*/ top__DOT__VGA_R;
    CData/*7:0*/ top__DOT__VGA_G;
    CData/*7:0*/ top__DOT__VGA_B;
    CData/*0:0*/ top__DOT__VGA_HS;
    CData/*0:0*/ top__DOT__VGA_VS;
    CData/*0:0*/ top__DOT__VGA_HB;
    CData/*0:0*/ top__DOT__VGA_VB;
    CData/*0:0*/ top__DOT__ioctl_download;
    CData/*0:0*/ top__DOT__ioctl_upload;
    CData/*0:0*/ top__DOT__ioctl_write;
    CData/*7:0*/ top__DOT__ioctl_dout;
    CData/*7:0*/ top__DOT__ioctl_din;
    CData/*7:0*/ top__DOT__ioctl_index;
    CData/*0:0*/ top__DOT__ioctl_wait;
    CData/*0:0*/ top__DOT__pause;
    CData/*7:0*/ top__DOT__audio;
    CData/*3:0*/ top__DOT__led;
    CData/*7:0*/ top__DOT__trakball;
    CData/*7:0*/ top__DOT__joystick;
    CData/*7:0*/ top__DOT__sw1;
    CData/*7:0*/ top__DOT__sw2;
    CData/*0:0*/ top__DOT__uut__DOT__clk_12mhz;
    CData/*0:0*/ top__DOT__uut__DOT__reset;
    CData/*0:0*/ top__DOT__uut__DOT__pause;
    CData/*7:0*/ top__DOT__uut__DOT__trakball_i;
    CData/*0:0*/ top__DOT__uut__DOT__flip_o;
    CData/*7:0*/ top__DOT__uut__DOT__joystick_i;
    CData/*7:0*/ top__DOT__uut__DOT__sw1_i;
    CData/*7:0*/ top__DOT__uut__DOT__sw2_i;
    CData/*7:0*/ top__DOT__uut__DOT__dn_data;
    CData/*0:0*/ top__DOT__uut__DOT__dn_wr;
    CData/*3:0*/ top__DOT__uut__DOT__led_o;
    CData/*0:0*/ top__DOT__uut__DOT__sync_o;
    CData/*0:0*/ top__DOT__uut__DOT__hsync_o;
    CData/*0:0*/ top__DOT__uut__DOT__vsync_o;
    CData/*0:0*/ top__DOT__uut__DOT__hblank_o;
    CData/*0:0*/ top__DOT__uut__DOT__vblank_o;
    CData/*7:0*/ top__DOT__uut__DOT__audio_o;
    CData/*0:0*/ top__DOT__uut__DOT__clk_6mhz_o;
    CData/*6:0*/ top__DOT__uut__DOT__hs_address;
    CData/*7:0*/ top__DOT__uut__DOT__hs_data_in;
    CData/*7:0*/ top__DOT__uut__DOT__hs_data_out;
    CData/*0:0*/ top__DOT__uut__DOT__hs_write;
    CData/*0:0*/ top__DOT__uut__DOT__hs_access;
    CData/*0:0*/ top__DOT__uut__DOT__s_12mhz_n;
    CData/*0:0*/ top__DOT__uut__DOT__phi0a;
    CData/*0:0*/ top__DOT__uut__DOT__phi0a_temp;
    CData/*0:0*/ top__DOT__uut__DOT__rom_n;
    CData/*0:0*/ top__DOT__uut__DOT__ram0_n;
    CData/*0:0*/ top__DOT__uut__DOT__steerclr_n;
    CData/*0:0*/ top__DOT__uut__DOT__watchdog_n;
    CData/*0:0*/ top__DOT__uut__DOT__out0_n;
    CData/*0:0*/ top__DOT__uut__DOT__pokey_n;
    CData/*0:0*/ top__DOT__uut__DOT__swrd_n;
    CData/*0:0*/ top__DOT__uut__DOT__pf_n;
    CData/*0:0*/ top__DOT__uut__DOT__coloram_n;
    CData/*0:0*/ top__DOT__uut__DOT__ea_read_n;
    CData/*0:0*/ top__DOT__uut__DOT__ea_ctrl_n;
    CData/*0:0*/ top__DOT__uut__DOT__ea_addr_n;
    CData/*0:0*/ top__DOT__uut__DOT__in0_n;
    CData/*0:0*/ top__DOT__uut__DOT__in1_n;
    CData/*0:0*/ top__DOT__uut__DOT__pframrd_n;
    CData/*0:0*/ top__DOT__uut__DOT__pfwr3_n;
    CData/*0:0*/ top__DOT__uut__DOT__pfwr2_n;
    CData/*0:0*/ top__DOT__uut__DOT__pfwr1_n;
    CData/*0:0*/ top__DOT__uut__DOT__pfwr0_n;
    CData/*0:0*/ top__DOT__uut__DOT__pfrd3_n;
    CData/*0:0*/ top__DOT__uut__DOT__pfrd2_n;
    CData/*0:0*/ top__DOT__uut__DOT__pfrd1_n;
    CData/*0:0*/ top__DOT__uut__DOT__pfrd0_n;
    CData/*0:0*/ top__DOT__uut__DOT__pac_n;
    CData/*7:0*/ top__DOT__uut__DOT__mpu_reset_cntr;
    CData/*0:0*/ top__DOT__uut__DOT__mpu_reset_n;
    CData/*0:0*/ top__DOT__uut__DOT__irq;
    CData/*0:0*/ top__DOT__uut__DOT__rw_n;
    CData/*7:0*/ top__DOT__uut__DOT__db_in;
    CData/*7:0*/ top__DOT__uut__DOT__db_out;
    CData/*7:0*/ top__DOT__uut__DOT__ram_out;
    CData/*7:0*/ top__DOT__uut__DOT__rom_out;
    CData/*7:0*/ top__DOT__uut__DOT__vprom_addr;
    CData/*3:0*/ top__DOT__uut__DOT__vprom_out;
    CData/*3:0*/ top__DOT__uut__DOT__vprom_reg;
    CData/*0:0*/ top__DOT__uut__DOT__vsync;
    CData/*0:0*/ top__DOT__uut__DOT__vblank;
    CData/*0:0*/ top__DOT__uut__DOT__hblank;
    CData/*0:0*/ top__DOT__uut__DOT__vreset;
    CData/*0:0*/ top__DOT__uut__DOT__hsync;
    CData/*0:0*/ top__DOT__uut__DOT__vsync_n;
    CData/*0:0*/ top__DOT__uut__DOT__hsync_n;
    CData/*0:0*/ top__DOT__uut__DOT__vblank_n;
    CData/*0:0*/ top__DOT__uut__DOT__hblank_n;
    CData/*0:0*/ top__DOT__uut__DOT__vreset_n;
    CData/*0:0*/ top__DOT__uut__DOT__s_2h;
    CData/*0:0*/ top__DOT__uut__DOT__s_4h;
    CData/*0:0*/ top__DOT__uut__DOT__s_16h;
    CData/*0:0*/ top__DOT__uut__DOT__s_64h;
    CData/*0:0*/ top__DOT__uut__DOT__s_128h;
    CData/*0:0*/ top__DOT__uut__DOT__s_256h;
    CData/*0:0*/ top__DOT__uut__DOT__s_1v;
    CData/*0:0*/ top__DOT__uut__DOT__s_2v;
    CData/*0:0*/ top__DOT__uut__DOT__s_4v;
    CData/*0:0*/ top__DOT__uut__DOT__s_8v;
    CData/*0:0*/ top__DOT__uut__DOT__s_32v;
    CData/*0:0*/ top__DOT__uut__DOT__s_64v;
    CData/*0:0*/ top__DOT__uut__DOT__s_128v;
    CData/*0:0*/ top__DOT__uut__DOT__s_4h_n;
    CData/*0:0*/ top__DOT__uut__DOT__s_8h_n;
    CData/*0:0*/ top__DOT__uut__DOT__s_256hd_n;
    CData/*0:0*/ top__DOT__uut__DOT__s_256h2d_n;
    CData/*0:0*/ top__DOT__uut__DOT__vblankd_n;
    CData/*0:0*/ top__DOT__uut__DOT__s_256h2d;
    CData/*0:0*/ top__DOT__uut__DOT__s_256hd;
    CData/*0:0*/ top__DOT__uut__DOT__vblankd;
    CData/*0:0*/ top__DOT__uut__DOT__pload_n;
    CData/*0:0*/ top__DOT__uut__DOT__write_n;
    CData/*0:0*/ top__DOT__uut__DOT__brw_n;
    CData/*7:0*/ top__DOT__uut__DOT__match_line;
    CData/*7:0*/ top__DOT__uut__DOT__match_sum;
    CData/*0:0*/ top__DOT__uut__DOT__match_sum_top;
    CData/*5:0*/ top__DOT__uut__DOT__match_sum_hold;
    CData/*3:0*/ top__DOT__uut__DOT__match_mux;
    CData/*0:0*/ top__DOT__uut__DOT__match_n;
    CData/*0:0*/ top__DOT__uut__DOT__match_true;
    CData/*3:0*/ top__DOT__uut__DOT__mga;
    CData/*7:0*/ top__DOT__uut__DOT__pf;
    CData/*1:0*/ top__DOT__uut__DOT__pf_sel;
    CData/*3:0*/ top__DOT__uut__DOT__pfa7654;
    CData/*3:0*/ top__DOT__uut__DOT__pfa3210;
    CData/*7:0*/ top__DOT__uut__DOT__pfa;
    CData/*7:0*/ top__DOT__uut__DOT__pf_out;
    CData/*0:0*/ top__DOT__uut__DOT__pf_addr_stamp;
    CData/*1:0*/ top__DOT__uut__DOT__gry;
    CData/*1:0*/ top__DOT__uut__DOT__y;
    CData/*1:0*/ top__DOT__uut__DOT__mr;
    CData/*7:0*/ top__DOT__uut__DOT__line_ram_addr;
    CData/*7:0*/ top__DOT__uut__DOT__line_ram_ctr;
    CData/*0:0*/ top__DOT__uut__DOT__line_ram_ctr_load;
    CData/*0:0*/ top__DOT__uut__DOT__line_ram_ctr_clr;
    CData/*7:0*/ top__DOT__uut__DOT__pf_mux1;
    CData/*7:0*/ top__DOT__uut__DOT__pf_mux0;
    CData/*7:0*/ top__DOT__uut__DOT__pf_shift1;
    CData/*7:0*/ top__DOT__uut__DOT__pf_shift0;
    CData/*1:0*/ top__DOT__uut__DOT__area;
    CData/*7:0*/ top__DOT__uut__DOT__pf_rom1_out;
    CData/*7:0*/ top__DOT__uut__DOT__pf_rom0_out;
    CData/*7:0*/ top__DOT__uut__DOT__pf_rom1_out_rev;
    CData/*7:0*/ top__DOT__uut__DOT__pf_rom0_out_rev;
    CData/*7:0*/ top__DOT__uut__DOT__pic;
    CData/*5:0*/ top__DOT__uut__DOT__hs_addr;
    CData/*7:0*/ top__DOT__uut__DOT__hs_out;
    CData/*7:0*/ top__DOT__uut__DOT__hs_data;
    CData/*0:0*/ top__DOT__uut__DOT__hs_cs1;
    CData/*0:0*/ top__DOT__uut__DOT__hs_c1;
    CData/*0:0*/ top__DOT__uut__DOT__hs_c2;
    CData/*0:0*/ top__DOT__uut__DOT__hs;
    CData/*0:0*/ top__DOT__uut__DOT__comp_sync;
    CData/*3:0*/ top__DOT__uut__DOT__rgbi;
    CData/*3:0*/ top__DOT__uut__DOT__coloram_out;
    CData/*3:0*/ top__DOT__uut__DOT__coloram_rgbi;
    CData/*0:0*/ top__DOT__uut__DOT__coloram_w_n;
    CData/*0:0*/ top__DOT__uut__DOT__coloren;
    CData/*0:0*/ top__DOT__uut__DOT__coloren_temp;
    CData/*1:0*/ top__DOT__uut__DOT__rama_sel;
    CData/*1:0*/ top__DOT__uut__DOT__rama_hi;
    CData/*1:0*/ top__DOT__uut__DOT__rama_lo;
    CData/*3:0*/ top__DOT__uut__DOT__rama;
    CData/*5:0*/ top__DOT__uut__DOT__audio;
    CData/*0:0*/ top__DOT__uut__DOT__mob_n;
    CData/*7:0*/ top__DOT__uut__DOT__joystick_out;
    CData/*3:0*/ top__DOT__uut__DOT__tra;
    CData/*3:0*/ top__DOT__uut__DOT__trb;
    CData/*0:0*/ top__DOT__uut__DOT__dir1;
    CData/*0:0*/ top__DOT__uut__DOT__dir2;
    CData/*7:0*/ top__DOT__uut__DOT__switch_out;
    CData/*0:0*/ top__DOT__uut__DOT__flip;
    CData/*0:0*/ top__DOT__uut__DOT__coin_ctr_r_drive;
    CData/*0:0*/ top__DOT__uut__DOT__coin_ctr_c_drive;
    CData/*0:0*/ top__DOT__uut__DOT__coin_ctr_l_drive;
    CData/*7:0*/ top__DOT__uut__DOT__playerin_out;
    CData/*7:0*/ top__DOT__uut__DOT__pokey_out;
    CData/*3:0*/ top__DOT__uut__DOT__pokey_ch0;
    CData/*3:0*/ top__DOT__uut__DOT__pokey_ch1;
    CData/*3:0*/ top__DOT__uut__DOT__pokey_ch2;
    CData/*3:0*/ top__DOT__uut__DOT__pokey_ch3;
    CData/*0:0*/ top__DOT__uut__DOT__hs_cs_ram;
    CData/*0:0*/ top__DOT__uut__DOT__hs_cs_earom;
    CData/*7:0*/ top__DOT__uut__DOT__hs_data_out_ram;
    CData/*7:0*/ top__DOT__uut__DOT__hs_data_out_earom;
    CData/*7:0*/ top__DOT__uut__DOT__v_counter;
    CData/*0:0*/ top__DOT__uut__DOT__v_counter_reset;
    CData/*0:0*/ top__DOT__uut__DOT__xxx1;
    CData/*0:0*/ top__DOT__uut__DOT__irq_n;
    CData/*0:0*/ top__DOT__uut__DOT__write2_n;
    CData/*0:0*/ top__DOT__uut__DOT__pf_romx_haddr;
    CData/*0:0*/ top__DOT__uut__DOT__pf_ce;
    CData/*0:0*/ top__DOT__uut__DOT__pf_ce_d;
    CData/*3:0*/ top__DOT__uut__DOT__pf_ce4_n;
    CData/*0:0*/ top__DOT__uut__DOT__js1_right;
    CData/*0:0*/ top__DOT__uut__DOT__js1_left;
    CData/*0:0*/ top__DOT__uut__DOT__js1_down;
    CData/*0:0*/ top__DOT__uut__DOT__js1_up;
    CData/*0:0*/ top__DOT__uut__DOT__js2_right;
    CData/*0:0*/ top__DOT__uut__DOT__js2_left;
    CData/*0:0*/ top__DOT__uut__DOT__js2_down;
    CData/*0:0*/ top__DOT__uut__DOT__js2_up;
    CData/*0:0*/ top__DOT__uut__DOT__coin_r;
    CData/*0:0*/ top__DOT__uut__DOT__coin_c;
    CData/*0:0*/ top__DOT__uut__DOT__coin_l;
    CData/*0:0*/ top__DOT__uut__DOT__self_test;
    CData/*0:0*/ top__DOT__uut__DOT__cocktail;
    CData/*0:0*/ top__DOT__uut__DOT__slam;
    CData/*0:0*/ top__DOT__uut__DOT__start1;
    CData/*0:0*/ top__DOT__uut__DOT__start2;
    CData/*0:0*/ top__DOT__uut__DOT__fire2;
    CData/*0:0*/ top__DOT__uut__DOT__fire1;
    CData/*7:0*/ top__DOT__uut__DOT__playerin_out0;
    CData/*7:0*/ top__DOT__uut__DOT__playerin_out1;
    CData/*7:0*/ top__DOT__uut__DOT__cc_latch;
    CData/*3:0*/ top__DOT__uut__DOT__tb_mux;
    CData/*0:0*/ top__DOT__uut__DOT__s_1_horiz_dir;
    CData/*0:0*/ top__DOT__uut__DOT__s_1_horiz_ck;
    CData/*0:0*/ top__DOT__uut__DOT__s_1_vert_dir;
    CData/*0:0*/ top__DOT__uut__DOT__s_1_vert_ck;
    CData/*0:0*/ top__DOT__uut__DOT__s_2_horiz_dir;
    CData/*0:0*/ top__DOT__uut__DOT__s_2_horiz_ck;
    CData/*0:0*/ top__DOT__uut__DOT__s_2_vert_dir;
    CData/*0:0*/ top__DOT__uut__DOT__s_2_vert_ck;
    CData/*0:0*/ top__DOT__uut__DOT__tb_h_dir;
    CData/*0:0*/ top__DOT__uut__DOT__tb_v_dir;
    CData/*0:0*/ top__DOT__uut__DOT__tb_h_reg;
    CData/*0:0*/ top__DOT__uut__DOT__tb_v_reg;
    CData/*3:0*/ top__DOT__uut__DOT__tb_h_ctr;
    CData/*3:0*/ top__DOT__uut__DOT__tb_v_ctr;
    CData/*7:0*/ top__DOT__uut__DOT__last_pokey_rd;
    CData/*0:0*/ top__DOT__uut__DOT__blank_disp_n;
    CData/*0:0*/ top__DOT__uut__DOT__gry0_or_1;
    CData/*0:0*/ top__DOT__uut__DOT__vprom__DOT__clk;
    CData/*0:0*/ top__DOT__uut__DOT__vprom__DOT__reset;
    CData/*7:0*/ top__DOT__uut__DOT__vprom__DOT__a;
    CData/*3:0*/ top__DOT__uut__DOT__vprom__DOT__d;
    CData/*3:0*/ top__DOT__uut__DOT__vprom__DOT__q;
    CData/*0:0*/ top__DOT__uut__DOT__rom__DOT__clk;
    CData/*0:0*/ top__DOT__uut__DOT__rom__DOT__reset;
    CData/*7:0*/ top__DOT__uut__DOT__rom__DOT__dout;
    CData/*0:0*/ top__DOT__uut__DOT__rom__DOT__cs_n;
    CData/*7:0*/ top__DOT__uut__DOT__rom__DOT__q;
    CData/*0:0*/ top__DOT__uut__DOT__ram__DOT__clk;
    CData/*0:0*/ top__DOT__uut__DOT__ram__DOT__reset;
    CData/*7:0*/ top__DOT__uut__DOT__ram__DOT__din;
    CData/*7:0*/ top__DOT__uut__DOT__ram__DOT__dout;
    CData/*0:0*/ top__DOT__uut__DOT__ram__DOT__cs_n;
    CData/*0:0*/ top__DOT__uut__DOT__ram__DOT__we_n;
    CData/*7:0*/ top__DOT__uut__DOT__ram__DOT__d;
    CData/*0:0*/ top__DOT__uut__DOT__ram__DOT__ram_read;
    CData/*0:0*/ top__DOT__uut__DOT__ram__DOT__ram_write;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__clk;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__reset_n;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__nmi;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__irq;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__so;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__rdy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__phi0;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__phi2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__rw_n;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__din;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__dout;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__reset;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__rw;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__rw_nxt;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__sync;
    CData/*4:0*/ top__DOT__uut__DOT__p6502__DOT__flags;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__reset;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__clk;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__nmi;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__irq;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__rdy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__so;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__di;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__dout;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__rw;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__rw_nxt;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__sync;
    CData/*4:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__flags;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__cres;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__creset;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__ir;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__dil;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__a_reg;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__x_reg;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__y_reg;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__sp_reg;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__nf;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__vf;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__bf;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__df;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__im;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__zf;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__cf;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__sr_reg;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__res;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__tmp;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__dout_nxt;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__prev_nmi;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__nmi_edge;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__any_int;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_reset;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_reset1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_reset2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_reset3;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_nmi1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_nmi2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_nmi3;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_nmi4;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_nmi5;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_ld_pch;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_exec;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_branch;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_dataFetch;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_update;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_afterWrite;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_ix1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_ix2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_iy1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_iy2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_abs1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_jmpi1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_jsr1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_jsr2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_pul;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_rts1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_rts2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_rts3;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_rti1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_rti2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_rti3;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__s_sync;
    CData/*2:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__cond;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__branch;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__taken;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__jmp;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__jmpi;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__php;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__pha;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__psh;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__plp;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__pla;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__pul;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__jsr;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__rts;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__rti;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__brk;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__nop;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__inx;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__iny;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__dex;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__dey;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__clc;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__cld;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__clv;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__cli;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__sec;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__sed;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__sei;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__tay;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__tya;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__tax;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__txa;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__tsx;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__txs;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__ror_a;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__lsr_a;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__rol_a;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__asl_a;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__ldx;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__stxx;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__ror;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__rol;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__lsr;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__asl;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__inc;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__dec;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__ldy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__styy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__cmp;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__ldy_i;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__cpy_i;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__ldx_i;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__cpx_i;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__mop;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__ix;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__zp;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__imm;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__abs;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__iy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__zpy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__zpx;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__absy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__absx;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__zpxy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__absxy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__sta;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__sty;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__stx;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__staxy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2m;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2x;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_us;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_us;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_us;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__axy_reg;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__axy_addo;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__sp_addo;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__firq;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__fbrk;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__nfo0;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__cfo0;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__vfo0;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__zfo0;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__nfo1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__cfo1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__vfo1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__zfo1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__nfo2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__cfo2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__zfo2;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_o;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_o;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_o;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__xyz_reg;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__takb;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__axy_adder__DOT__op;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__axy_adder__DOT__ci;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__axy_adder__DOT__o;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__axy_adder__DOT__co;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__axy_adder__DOT__v;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__spadder__DOT__op;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__spadder__DOT__ci;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__spadder__DOT__o;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__spadder__DOT__co;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__spadder__DOT__v;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__ir;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__a_reg;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__x_reg;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__y_reg;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__d;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__ni;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__vi;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__zi;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__ci;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__n;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__v;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__z;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__c;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__w_bit;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__res;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__ldy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__cpy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__cpx;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__bitt;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__ir;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__dec;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__ni;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__vi;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__zi;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__ci;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__a_reg;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__d;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__o;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__n;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__v;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__z;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__c;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__adc_o;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sbc_o;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__cmp_o;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__adc_c;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sbc_c;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__cmp_c;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__adc;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sbc;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__cmp;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sta;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__dec;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__ci;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__a;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__b;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__o;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__c;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__c4;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__c8;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__dec_sum;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na0__DOT__dec;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na0__DOT__ci;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na0__DOT__a;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na0__DOT__b;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na0__DOT__o;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na0__DOT__c;
    CData/*5:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na0__DOT__tmp1;
    CData/*4:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na0__DOT__tmp2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na0__DOT__hc1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na0__DOT__hc2;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na0__DOT__sum;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na1__DOT__dec;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na1__DOT__ci;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na1__DOT__a;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na1__DOT__b;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na1__DOT__o;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na1__DOT__c;
    CData/*5:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na1__DOT__tmp1;
    CData/*4:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na1__DOT__tmp2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na1__DOT__hc1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na1__DOT__hc2;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__na1__DOT__sum;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__dec;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ci;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__a;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__b;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__o;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__c;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__c4;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__c8;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__dec_dif;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns0__DOT__dec;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns0__DOT__ci;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns0__DOT__a;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns0__DOT__b;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns0__DOT__o;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns0__DOT__c;
    CData/*5:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns0__DOT__tmp1;
    CData/*4:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns0__DOT__tmp2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns0__DOT__hb1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns0__DOT__hb2;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns0__DOT__dif;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns1__DOT__dec;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns1__DOT__ci;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns1__DOT__a;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns1__DOT__b;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns1__DOT__o;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns1__DOT__c;
    CData/*5:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns1__DOT__tmp1;
    CData/*4:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns1__DOT__tmp2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns1__DOT__hb1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns1__DOT__hb2;
    CData/*3:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__ns1__DOT__dif;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__ir;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__ldx;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__stxx;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__d;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__ci;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__ni;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__zi;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__c;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__n;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__z;
    CData/*7:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__o;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__sc;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__d_shift;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__reset;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__creset;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__clk;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__rdy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__any_int;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__grp0;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__grp1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__grp2x;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__grp2m;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__brk;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__mop;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__rti;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__rts;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__pul;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__psh;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__jsr;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__jmp;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__jmpi;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__branch;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__staxy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__ix;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__iy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__absxy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__imm;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__zpxy;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_reset;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_reset1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_reset2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_reset3;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_nmi1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_nmi2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_nmi3;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_nmi4;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_nmi5;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_ld_pch;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_exec;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_branch;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_dataFetch;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_update;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_afterWrite;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_ix1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_ix2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_iy1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_iy2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_abs1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_jmpi1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_jsr1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_jsr2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_pul;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_rts1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_rts2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_rts3;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_rti1;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_rti2;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_rti3;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__seq0__DOT__s_sync;
    CData/*0:0*/ top__DOT__uut__DOT__pf_rom1__DOT__clk;
    CData/*0:0*/ top__DOT__uut__DOT__pf_rom1__DOT__reset;
    CData/*7:0*/ top__DOT__uut__DOT__pf_rom1__DOT__d;
    CData/*7:0*/ top__DOT__uut__DOT__pf_rom1__DOT__q;
    CData/*0:0*/ top__DOT__uut__DOT__pf_rom0__DOT__clk;
    CData/*0:0*/ top__DOT__uut__DOT__pf_rom0__DOT__reset;
    CData/*7:0*/ top__DOT__uut__DOT__pf_rom0__DOT__d;
    CData/*7:0*/ top__DOT__uut__DOT__pf_rom0__DOT__q;
    CData/*0:0*/ top__DOT__uut__DOT__pf_ram__DOT__clk_a;
    CData/*0:0*/ top__DOT__uut__DOT__pf_ram__DOT__clk_b;
    CData/*0:0*/ top__DOT__uut__DOT__pf_ram__DOT__reset;
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__addr_a;
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__din_a;
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__dout_a;
    CData/*3:0*/ top__DOT__uut__DOT__pf_ram__DOT__ce_a;
    CData/*3:0*/ top__DOT__uut__DOT__pf_ram__DOT__we_a;
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__addr_b;
    CData/*3:0*/ top__DOT__uut__DOT__pf_ram__DOT__ce_b;
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__d_a;
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__d_a0;
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__d_a1;
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__d_a2;
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__d_a3;
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__d_b3;
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__d_b2;
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__d_b1;
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__d_b0;
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__r_a;
    CData/*3:0*/ top__DOT__uut__DOT__pf_ram__DOT__r_w;
    CData/*0:0*/ top__DOT__uut__DOT__pf_ram__DOT__ram_read_a;
    CData/*0:0*/ top__DOT__uut__DOT__pf_ram__DOT__ram_read_b;
    CData/*0:0*/ top__DOT__uut__DOT__hs_ram__DOT__clk;
    CData/*5:0*/ top__DOT__uut__DOT__hs_ram__DOT__a;
    CData/*7:0*/ top__DOT__uut__DOT__hs_ram__DOT__dout;
    CData/*7:0*/ top__DOT__uut__DOT__hs_ram__DOT__din;
    CData/*0:0*/ top__DOT__uut__DOT__hs_ram__DOT__rclk;
    CData/*0:0*/ top__DOT__uut__DOT__hs_ram__DOT__c1;
    CData/*0:0*/ top__DOT__uut__DOT__hs_ram__DOT__c2;
    CData/*0:0*/ top__DOT__uut__DOT__hs_ram__DOT__cs1;
    CData/*7:0*/ top__DOT__uut__DOT__hs_ram__DOT__d;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__phi2;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__reset;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__r_w_n;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__cs0_n;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__cs1_n;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__a;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__d_in;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__d_out;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__p;
    CData/*5:0*/ top__DOT__uut__DOT__pokey__DOT__aud;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__we;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__stb;
    CData/*5:0*/ top__DOT__uut__DOT__pokey__DOT__audout;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__rst_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__clk_i;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__adr_i;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__dat_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__we_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__stb_i;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__key_code;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__key_pressed;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__key_shift;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__key_break;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__serout_ack_i;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__serin;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__serin_rdy_i;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__p_i;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__dat_o;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__ack_o;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__irq;
    CData/*5:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__audout;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__serout;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__serout_rdy_o;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__serin_ack_o;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__last_key_pressed;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__last_key_break;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__last_serin_rdy_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__last_serout_ack_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__rst;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__start_timer;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__irqen;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__irqst;
    CData/*1:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__rst_bits;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__poly9;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__fast_ch0;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__fast_ch2;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__ch01;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__ch23;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__fi02;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__fi13;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__base15;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__audf_we;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__audc_we;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__start;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__cnt_en;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__borrow;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__poly4;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__poly5;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__poly17;
    CData/*2:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__poly4_shift;
    CData/*2:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__poly5_shift;
    CData/*2:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__poly17_shift;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__base;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__audout0;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__audout1;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__audout2;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__audout3;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__random;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__pot_done;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__pot_count;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_base__DOT__rst;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_base__DOT__clk_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_base__DOT__base15;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_base__DOT__out;
    CData/*5:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_base__DOT__div57;
    CData/*1:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_base__DOT__div4;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly4__DOT__rst;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly4__DOT__clk_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly4__DOT__out;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly4__DOT__shift;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly5__DOT__rst;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly5__DOT__clk_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly5__DOT__out;
    CData/*4:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly5__DOT__shift;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly17__DOT__rst;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly17__DOT__clk_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly17__DOT__short;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly17__DOT__out;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly17__DOT__random;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly17__DOT__new_bit;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly17__DOT__last_short;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr0__DOT__clk_i;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr0__DOT__dat_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr0__DOT__freq_ld;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr0__DOT__start;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr0__DOT__cnt_en;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr0__DOT__out;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr0__DOT__borrow;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr0__DOT__freq;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr1__DOT__clk_i;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr1__DOT__dat_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr1__DOT__freq_ld;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr1__DOT__start;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr1__DOT__cnt_en;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr1__DOT__out;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr1__DOT__borrow;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr1__DOT__freq;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr2__DOT__clk_i;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr2__DOT__dat_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr2__DOT__freq_ld;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr2__DOT__start;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr2__DOT__cnt_en;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr2__DOT__out;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr2__DOT__borrow;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr2__DOT__freq;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr3__DOT__clk_i;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr3__DOT__dat_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr3__DOT__freq_ld;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr3__DOT__start;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr3__DOT__cnt_en;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr3__DOT__out;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr3__DOT__borrow;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_ctr3__DOT__freq;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__rst;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__clk_i;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__dat_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__audc_we;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__poly4;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__poly5;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__poly17;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__in;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__filter_en;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__filter_in;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__out;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__vol;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__vol_only;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__no_poly5;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__poly4_sel;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__no_poly17_4;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__nf;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__filter_reg;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__change;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout0__DOT__ch_out;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__rst;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__clk_i;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__dat_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__audc_we;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__poly4;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__poly5;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__poly17;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__in;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__filter_en;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__filter_in;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__out;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__vol;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__vol_only;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__no_poly5;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__poly4_sel;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__no_poly17_4;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__nf;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__filter_reg;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__change;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout1__DOT__ch_out;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__rst;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__clk_i;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__dat_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__audc_we;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__poly4;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__poly5;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__poly17;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__in;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__filter_en;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__filter_in;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__out;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__vol;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__vol_only;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__no_poly5;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__poly4_sel;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__no_poly17_4;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__nf;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__filter_reg;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__change;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout2__DOT__ch_out;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__rst;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__clk_i;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__dat_i;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__audc_we;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__poly4;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__poly5;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__poly17;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__in;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__filter_en;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__filter_in;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__out;
    CData/*3:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__vol;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__vol_only;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__no_poly5;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__poly4_sel;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__no_poly17_4;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__nf;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__filter_reg;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__change;
    CData/*0:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_audout3__DOT__ch_out;
    CData/*0:0*/ top__DOT__uut__DOT__color_ram__DOT__clk_a;
    CData/*0:0*/ top__DOT__uut__DOT__color_ram__DOT__clk_b;
    CData/*0:0*/ top__DOT__uut__DOT__color_ram__DOT__reset;
    CData/*3:0*/ top__DOT__uut__DOT__color_ram__DOT__addr_a;
    CData/*3:0*/ top__DOT__uut__DOT__color_ram__DOT__dout_a;
    CData/*3:0*/ top__DOT__uut__DOT__color_ram__DOT__din_a;
    CData/*0:0*/ top__DOT__uut__DOT__color_ram__DOT__we_n_a;
    CData/*3:0*/ top__DOT__uut__DOT__color_ram__DOT__addr_b;
    CData/*3:0*/ top__DOT__uut__DOT__color_ram__DOT__dout_b;
    CData/*3:0*/ top__DOT__uut__DOT__color_ram__DOT__d_a;
    CData/*3:0*/ top__DOT__uut__DOT__color_ram__DOT__d_b;
    SData/*11:0*/ top__DOT__inputs;
    SData/*8:0*/ top__DOT__rgb;
    SData/*9:0*/ top__DOT__playerinput;
    SData/*9:0*/ top__DOT__uut__DOT__playerinput_i;
    SData/*15:0*/ top__DOT__uut__DOT__dn_addr;
    SData/*8:0*/ top__DOT__uut__DOT__rgb_o;
    SData/*9:0*/ top__DOT__uut__DOT__adecode;
    SData/*15:0*/ top__DOT__uut__DOT__ab;
    SData/*15:0*/ top__DOT__uut__DOT__pdf;
    SData/*13:0*/ top__DOT__uut__DOT__pfd_hold;
    SData/*13:0*/ top__DOT__uut__DOT__pfd_hold2;
    SData/*10:0*/ top__DOT__uut__DOT__pf_rom1_addr;
    SData/*10:0*/ top__DOT__uut__DOT__pf_rom0_addr;
    SData/*11:0*/ top__DOT__uut__DOT__h_counter;
    SData/*12:0*/ top__DOT__uut__DOT__rom__DOT__a;
    SData/*9:0*/ top__DOT__uut__DOT__ram__DOT__a;
    SData/*9:0*/ top__DOT__uut__DOT__ram__DOT__addr;
    SData/*15:0*/ top__DOT__uut__DOT__p6502__DOT__a;
    SData/*15:0*/ top__DOT__uut__DOT__p6502__DOT__ma;
    SData/*15:0*/ top__DOT__uut__DOT__p6502__DOT__ma_nxt;
    SData/*15:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__ma;
    SData/*15:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__ma_nxt;
    SData/*15:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__pc_reg;
    SData/*15:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__pc_nxt;
    SData/*15:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__vec;
    SData/*8:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__axy_adder__DOT__a;
    SData/*8:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__axy_adder__DOT__b;
    SData/*9:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__axy_adder__DOT__sum;
    SData/*8:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__spadder__DOT__a;
    SData/*8:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__spadder__DOT__b;
    SData/*9:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__spadder__DOT__sum;
    SData/*8:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__w_cpy;
    SData/*8:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__w_cpx;
    SData/*8:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__cmp_tmp;
    SData/*9:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__bin_sum;
    SData/*9:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__bin_dif;
    SData/*10:0*/ top__DOT__uut__DOT__pf_rom1__DOT__a;
    SData/*10:0*/ top__DOT__uut__DOT__pf_rom0__DOT__a;
    SData/*11:0*/ top__DOT__uut__DOT__pf_ram__DOT__b_a;
    IData/*24:0*/ top__DOT__ioctl_addr;
    IData/*31:0*/ top__DOT__uut__DOT__STDERR;
    IData/*31:0*/ top__DOT__uut__DOT__pfd;
    IData/*31:0*/ top__DOT__uut__DOT__ram__DOT__j;
    IData/*31:0*/ top__DOT__uut__DOT__p6502__DOT__state;
    IData/*31:0*/ top__DOT__uut__DOT__p6502__DOT__pccount;
    IData/*31:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__state;
    IData/*31:0*/ top__DOT__uut__DOT__pf_ram__DOT__dout_b;
    IData/*31:0*/ top__DOT__uut__DOT__pf_ram__DOT__j;
    IData/*31:0*/ top__DOT__uut__DOT__pf_ram__DOT__data_file;
    IData/*31:0*/ top__DOT__uut__DOT__pf_ram__DOT__f_a;
    IData/*31:0*/ top__DOT__uut__DOT__pf_ram__DOT__f_d;
    IData/*31:0*/ top__DOT__uut__DOT__pf_ram__DOT__r;
    IData/*31:0*/ top__DOT__uut__DOT__hs_ram__DOT__STDERR;
    IData/*31:0*/ top__DOT__uut__DOT__hs_ram__DOT__j;
    IData/*31:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__ctr_out;
    IData/*31:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__i;
    IData/*31:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__irq_i;
    IData/*16:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__u_poly17__DOT__shift;
    IData/*31:0*/ top__DOT__uut__DOT__color_ram__DOT__j;
    CData/*1:0*/ top__DOT__uut__DOT__line_ram[256];
    CData/*7:0*/ top__DOT__uut__DOT__ram__DOT__mem[1024];
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__ram3[256];
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__ram2[256];
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__ram1[256];
    CData/*7:0*/ top__DOT__uut__DOT__pf_ram__DOT__ram0[256];
    CData/*7:0*/ top__DOT__uut__DOT__hs_ram__DOT__mem[64];
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT__pot_cntr[8];
    CData/*3:0*/ top__DOT__uut__DOT__color_ram__DOT__ram[16];
    
    // LOCAL VARIABLES
    // Internals; generally not touched by application code
    CData/*3:0*/ top__DOT____Vcellout__uut__led_o;
    CData/*3:0*/ top__DOT__uut__DOT____Vcellinp__pf_ram__we_a;
    CData/*3:0*/ top__DOT__uut__DOT____Vcellinp__pf_ram__ce_a;
    CData/*7:0*/ top__DOT__uut__DOT____Vcellinp__pf_ram__addr_a;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT____Vcellinp__axy_adder__op;
    CData/*0:0*/ top__DOT__uut__DOT__p6502__DOT__bc6502__DOT____Vcellinp__spadder__op;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT____Vcellout__u_ctr0____pinNumber6;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT____Vcellout__u_ctr1____pinNumber6;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT____Vcellout__u_ctr2____pinNumber6;
    CData/*7:0*/ top__DOT__uut__DOT__pokey__DOT__pokey__DOT____Vcellout__u_ctr3____pinNumber6;
    CData/*6:0*/ __Vtableidx3;
    CData/*7:0*/ __Vdlyvdim0__top__DOT__uut__DOT__line_ram__v0;
    CData/*1:0*/ __Vdlyvval__top__DOT__uut__DOT__line_ram__v0;
    CData/*0:0*/ __Vdlyvset__top__DOT__uut__DOT__line_ram__v0;
    CData/*7:0*/ __Vdly__top__DOT__uut__DOT__pf_shift1;
    CData/*7:0*/ __Vdly__top__DOT__uut__DOT__pf_shift0;
    CData/*3:0*/ __Vdlyvdim0__top__DOT__uut__DOT__color_ram__DOT__ram__v0;
    CData/*3:0*/ __Vdlyvval__top__DOT__uut__DOT__color_ram__DOT__ram__v0;
    CData/*0:0*/ __Vdlyvset__top__DOT__uut__DOT__color_ram__DOT__ram__v0;
    CData/*7:0*/ __Vdly__top__DOT__uut__DOT__mpu_reset_cntr;
    CData/*0:0*/ __VinpClk__TOP__top__DOT__uut__DOT__hs_clk;
    CData/*0:0*/ __VinpClk__TOP__top__DOT__uut__DOT__hsync_reset;
    CData/*0:0*/ __VinpClk__TOP__top__DOT__uut__DOT__tb_v_ctr_clr;
    CData/*0:0*/ __VinpClk__TOP__top__DOT__uut__DOT__tb_h_ctr_clr;
    CData/*0:0*/ __VinpClk__TOP__top__DOT__uut__DOT__mpu_reset;
    CData/*0:0*/ __VinpClk__TOP__top__DOT__uut__DOT__hs_set;
    CData/*0:0*/ __VinpClk__TOP__top__DOT__uut__DOT__irqres_n;
    CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__top__DOT__uut__DOT__hs_clk;
    CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__top__DOT__uut__DOT__hsync_reset;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__s_8h;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__s_6mhz;
    CData/*0:0*/ __Vclklast__TOP__reset;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__s_1h;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__s_12mhz;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__s_6mhz_n;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__mpu_clk;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__s_6_12;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__blank_clk;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__tb_v_ck;
    CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__top__DOT__uut__DOT__tb_v_ctr_clr;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__tb_h_ck;
    CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__top__DOT__uut__DOT__tb_h_ctr_clr;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__phi0;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__phi2;
    CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__top__DOT__uut__DOT__mpu_reset;
    CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__top__DOT__uut__DOT__hs_set;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__s_32h;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__s_256h_n;
    CData/*0:0*/ __Vclklast__TOP____VinpClk__TOP__top__DOT__uut__DOT__irqres_n;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__s_16v;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__ea_addr_clk;
    CData/*0:0*/ __Vclklast__TOP__top__DOT__uut__DOT__ea_ctrl_clk;
    CData/*0:0*/ __Vchglast__TOP__top__DOT__uut__DOT__irqres_n;
    CData/*0:0*/ __Vchglast__TOP__top__DOT__uut__DOT__ea_addr_n;
    CData/*0:0*/ __Vchglast__TOP__top__DOT__uut__DOT__mpu_reset;
    CData/*0:0*/ __Vchglast__TOP__top__DOT__uut__DOT__hsync_reset;
    CData/*0:0*/ __Vchglast__TOP__top__DOT__uut__DOT__hs_clk;
    CData/*0:0*/ __Vchglast__TOP__top__DOT__uut__DOT__hs_set;
    CData/*0:0*/ __Vchglast__TOP__top__DOT__uut__DOT__tb_h_ctr_clr;
    CData/*0:0*/ __Vchglast__TOP__top__DOT__uut__DOT__tb_v_ctr_clr;
    SData/*11:0*/ __Vchglast__TOP__top__DOT__uut__DOT__h_counter;
    static CData/*3:0*/ __Vtable1_top__DOT__uut__DOT__vprom__DOT__q[256];
    static CData/*7:0*/ __Vtable2_top__DOT__uut__DOT__rom__DOT__q[16384];
    static CData/*0:0*/ __Vtable3_top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__takb[128];
    static CData/*7:0*/ __Vtable4_top__DOT__uut__DOT__pf_rom1__DOT__q[2048];
    static CData/*7:0*/ __Vtable5_top__DOT__uut__DOT__pf_rom0__DOT__q[2048];
    
    // INTERNAL VARIABLES
    // Internals; generally not touched by application code
    Vtop__Syms* __VlSymsp;  // Symbol table
    
    // PARAMETERS
    // Parameters marked /*verilator public*/ for use by application code
    enum _IDatatop__DOT__uut__DOT__p6502__DOT__bc6502__DOT__ABW { top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__ABW = 0x10U};
    enum _IDatatop__DOT__uut__DOT__p6502__DOT__bc6502__DOT__DBW { top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__DBW = 8U};
    enum _IDatatop__DOT__uut__DOT__p6502__DOT__bc6502__DOT__axy_adder__DOT__DBW { top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__axy_adder__DOT__DBW = 8U};
    enum _IDatatop__DOT__uut__DOT__p6502__DOT__bc6502__DOT__spadder__DOT__DBW { top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__spadder__DOT__DBW = 8U};
    enum _IDatatop__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__DBW { top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp0_inst__DOT__DBW = 8U};
    enum _IDatatop__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__DBW { top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__DBW = 8U};
    enum _IDatatop__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__dec_support { top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__add0__DOT__dec_support = 1U};
    enum _IDatatop__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__dec_support { top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp1_inst__DOT__sub0__DOT__dec_support = 1U};
    enum _IDatatop__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__DBW { top__DOT__uut__DOT__p6502__DOT__bc6502__DOT__grp2_inst__DOT__DBW = 8U};
    enum _IDatatop__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_BREAK { top__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_BREAK = 7U};
    enum _IDatatop__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_KEY { top__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_KEY = 6U};
    enum _IDatatop__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_SERIN { top__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_SERIN = 5U};
    enum _IDatatop__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_SEROUT { top__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_SEROUT = 4U};
    enum _IDatatop__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_SERFIN { top__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_SERFIN = 3U};
    enum _IDatatop__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_TIMER4 { top__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_TIMER4 = 2U};
    enum _IDatatop__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_TIMER2 { top__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_TIMER2 = 1U};
    enum _IDatatop__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_TIMER1 { top__DOT__uut__DOT__pokey__DOT__pokey__DOT__IRQ_TIMER1 = 1U};
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vtop);  ///< Copying not allowed
  public:
    /// Construct the model; called by application code
    /// The special name  may be used to make a wrapper with a
    /// single model invisible with respect to DPI scope names.
    Vtop(const char* name = "TOP");
    /// Destroy the model; called (often implicitly) by application code
    ~Vtop();
    
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval();
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    
    // INTERNAL METHODS
  private:
    static void _eval_initial_loop(Vtop__Syms* __restrict vlSymsp);
  public:
    void __Vconfigure(Vtop__Syms* symsp, bool first);
  private:
    static QData _change_request(Vtop__Syms* __restrict vlSymsp);
  public:
    static void _combo__TOP__17(Vtop__Syms* __restrict vlSymsp);
    static void _combo__TOP__3(Vtop__Syms* __restrict vlSymsp);
    static void _combo__TOP__35(Vtop__Syms* __restrict vlSymsp);
    static void _combo__TOP__46(Vtop__Syms* __restrict vlSymsp);
    static void _combo__TOP__51(Vtop__Syms* __restrict vlSymsp);
    static void _combo__TOP__53(Vtop__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    static void _eval(Vtop__Syms* __restrict vlSymsp);
  private:
#ifdef VL_DEBUG
    void _eval_debug_assertions();
#endif  // VL_DEBUG
  public:
    static void _eval_initial(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _eval_settle(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__1(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _multiclk__TOP__28(Vtop__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__33(Vtop__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__37(Vtop__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__38(Vtop__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__42(Vtop__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__44(Vtop__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__47(Vtop__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__48(Vtop__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__49(Vtop__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__54(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__10(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__11(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__12(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__13(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__14(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__15(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__16(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__19(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__21(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__22(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__23(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__24(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__25(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__26(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__27(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__29(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__30(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__31(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__32(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__34(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__36(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__39(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__4(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__40(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__41(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__43(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__45(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__5(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__50(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__52(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__6(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__7(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__8(Vtop__Syms* __restrict vlSymsp);
    static void _sequent__TOP__9(Vtop__Syms* __restrict vlSymsp);
    static void _settle__TOP__2(Vtop__Syms* __restrict vlSymsp) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
